[project]
name = "github-stars-monitor"
version = "0.1.0"
description = "Collect stars from recently created repositories"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.10.4",
    "dbt-duckdb>=1.9.4",
    "dlt[duckdb]>=1.13.0",
    "fire>=0.7.0",
    "pre-commit>=4.2.0",
]
